#pragma once

#define BITS_IN_A_BYTE 8
#define MS_DEBUG_MALLOC_INIT_VALUE (-842150451) //WARNING: not portable, but used only for testing
#define A_THOUSAND 1000
#define A_MILLION 1000000
#define A_BILLION 1000000000
#define SECONDS_IN_A_MINUTE (60)
#define MILLIS_IN_A_SECOND A_THOUSAND
#define TENTHS_OF_MS_IN_A_SECOND (10*MILLIS_IN_A_SECOND)
#define TENTHS_OF_MS_IN_A_MILLI (10)
#define MICROS_IN_A_SECOND A_MILLION
#define NANOS_IN_A_SECOND A_BILLION
#define MICROS_IN_A_MILLI A_THOUSAND
#define NANOS_IN_A_MILLI A_MILLION
#define NANOS_IN_A_MICRO A_THOUSAND
#define NATURAL_RETURN_ERROR (-1)



